---
- job:
    name: kollacli-tox-functional
    parent: openstack-tox
    description: |
      Run tox-based functional tests for the OpenStack Kolla-cli project.
      Uses tox with the ``functional`` environment.
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/source/.*$
      - ^releasenotes/.*$
    vars:
      tox_envlist: functional
    timeout: 3600

- job:
    name: kollacli-tox-functional-py36
    parent: openstack-tox
    description: |
      Run tox-based py36 functional tests for the OpenStack Kolla-cli project.
      Uses tox with the ``functional`` environment.
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/source/.*$
      - ^releasenotes/.*$
    vars:
      tox_envlist: functional-py36
    timeout: 3600

- job:
    name: kollacli-tox-mypy
    parent: openstack-tox
    description: |
      Run static mypy type checker for the OpenStack Kolla-cli project.
    vars:
      tox_envlist: mypy
    timeout: 3600

- project:
    templates:
        - openstack-cover-jobs
        - openstack-python3-train-jobs
    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py27
        - kollacli-tox-mypy
        - kollacli-tox-functional
        - kollacli-tox-functional-py36
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py27
        - kollacli-tox-mypy
        - kollacli-tox-functional
        - kollacli-tox-functional-py36
